filename = "final.h5";
nx = h5read(filename,"/Nx");
ny = h5read(filename,"/Ny");
nz = h5read(filename,"/Nz");
gamma = h5read(filename,"/Gamma");
gamma = reshape(gamma,nx,ny,nz);
rho = h5read(filename,"/Density_0");
rho = reshape(rho,nx,ny,nz);
V   = h5read(filename,"/Velocity_0");
vx  = V(1:3:end);
vy  = V(2:3:end);
vz  = V(3:3:end);
vx  = reshape(vx,nx,ny,nz);
vy  = reshape(vy,nx,ny,nz);
vz  = reshape(vz,nx,ny,nz);
[x y z] = meshgrid(1:nx, 1:ny, 1:nz);
x = double(x);
y = double(y);
z = double(z);
[sx sy sz] = meshgrid(nx-100, ny/2-2:ny/2+2, nz/2-2:nz/2+2);
sx = double(sx);
sy = double(sy);
sz = double(sz);
streamslice(x,y,z,vx,vy,vz,sx,sy,sz);
%quiver3(x,y,z,vx,vy,vz);